export const apiKeys = {
    item: () => ['item'],
    itemHealth: () => [...apiKeys.item(), 'health'],
    itemAbilities: () => [...apiKeys.item(), 'abilities'],
    itemMetrics: () => [...apiKeys.item(), 'metrics'],
    itemMetricDetails: (name: string, tags: Record<string, string>) => [...apiKeys.itemMetrics(), name, tags],
    itemEnv: () => [...apiKeys.item(), 'env'],
    itemLoggers: () => [...apiKeys.item(), 'loggers'],
    itemLogfile: () => [...apiKeys.item(), 'logfile'],
    itemStartup: () => [...apiKeys.item(), 'startup'],
    itemBeans: () => [...apiKeys.item(), 'beans'],
    itemMappings: () => [...apiKeys.item(), 'mappings'],
    itemHttpExchanges: () => [...apiKeys.item(), 'httpExchanges'],
    itemPrometheus: () => [...apiKeys.item(), 'prometheus'],
    itemConditions: () => [...apiKeys.item(), 'conditions'],
    itemConfigProps: () => [...apiKeys.item(), 'configProps'],
    itemCaches: () => [...apiKeys.item(), 'caches'],
    itemScheduledTasks: () => [...apiKeys.item(), 'scheduledTasks'],
    itemScheduledTasksCron: () => [...apiKeys.itemScheduledTasks(), 'cron'],
    itemScheduledTasksFixedDelay: () => [...apiKeys.itemScheduledTasks(), 'fixedDelay'],
    itemScheduledTasksFixedRate: () => [...apiKeys.itemScheduledTasks(), 'fixedRate'],
    itemScheduledTasksFixed: (type: string) => [...apiKeys.itemScheduledTasks(), 'fixed', type],
    itemScheduledTasksCustom: () => [...apiKeys.itemScheduledTasks(), 'custom'],
    itemHttpRequestStatistics: (instanceId: string) => [...apiKeys.item(), 'httpRequestStatistics', instanceId],
    itemQuartz: (instanceId: string) => [...apiKeys.item(), 'quartz', instanceId],
    itemQuartzJob: (group: string, name: string) => [...apiKeys.item(), 'quartz', 'jobs', group, name],
    itemQuartzJobs: (group: string) => [...apiKeys.item(), 'quartz', 'jobs', group],
    itemQuartzTriggers: (group: string) => [...apiKeys.item(), 'quartz', 'triggers', group],
    itemQuartzTrigger: (group: string, name: string) => [...apiKeys.item(), 'quartz', 'triggers', group, name],
    itemSessions: () => [...apiKeys.item(), 'sessions'],
    itemTogglz: (instanceId: string) => [...apiKeys.item(), 'togglz', instanceId],
    itemThreaddump: () => [...apiKeys.item(), 'threaddump'],
    metricLatest: (instanceId: string, metricName: string) => [...apiKeys.itemMetrics(), 'latest', instanceId, metricName],
}

export type BasicValue = | string | number | boolean | null

export type JsonValue = | JsonValue[] | { [key: string]: JsonValue }