/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authConnectRouteImport } from './routes/(auth)/connect'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedBeansIndexRouteImport } from './routes/_authenticated/beans/index'
import { Route as AuthenticatedCachesIndexRouteImport } from './routes/_authenticated/caches/index'
import { Route as AuthenticatedConditionsIndexRouteImport } from './routes/_authenticated/conditions/index'
import { Route as AuthenticatedConfigpropsIndexRouteImport } from './routes/_authenticated/configprops/index'
import { Route as AuthenticatedEnvIndexRouteImport } from './routes/_authenticated/env/index'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedHealthIndexRouteImport } from './routes/_authenticated/health/index'
import { Route as AuthenticatedLoggersIndexRouteImport } from './routes/_authenticated/loggers/index'
import { Route as AuthenticatedMappingsIndexRouteImport } from './routes/_authenticated/mappings/index'
import { Route as AuthenticatedMetricsIndexRouteImport } from './routes/_authenticated/metrics/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authConnectRoute = authConnectRouteImport.update({
  id: '/(auth)/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBeansIndexRoute = AuthenticatedBeansIndexRouteImport.update({
  id: '/beans/',
  path: '/beans/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCachesIndexRoute =
  AuthenticatedCachesIndexRouteImport.update({
    id: '/caches/',
    path: '/caches/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConditionsIndexRoute =
  AuthenticatedConditionsIndexRouteImport.update({
    id: '/conditions/',
    path: '/conditions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfigpropsIndexRoute =
  AuthenticatedConfigpropsIndexRouteImport.update({
    id: '/configprops/',
    path: '/configprops/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnvIndexRoute = AuthenticatedEnvIndexRouteImport.update({
  id: '/env/',
  path: '/env/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHealthIndexRoute =
  AuthenticatedHealthIndexRouteImport.update({
    id: '/health/',
    path: '/health/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLoggersIndexRoute =
  AuthenticatedLoggersIndexRouteImport.update({
    id: '/loggers/',
    path: '/loggers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMappingsIndexRoute =
  AuthenticatedMappingsIndexRouteImport.update({
    id: '/mappings/',
    path: '/mappings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetricsIndexRoute =
  AuthenticatedMetricsIndexRouteImport.update({
    id: '/metrics/',
    path: '/metrics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/connect': typeof authConnectRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/beans/': typeof AuthenticatedBeansIndexRoute
  '/caches/': typeof AuthenticatedCachesIndexRoute
  '/conditions/': typeof AuthenticatedConditionsIndexRoute
  '/configprops/': typeof AuthenticatedConfigpropsIndexRoute
  '/env/': typeof AuthenticatedEnvIndexRoute
  '/health/': typeof AuthenticatedHealthIndexRoute
  '/loggers/': typeof AuthenticatedLoggersIndexRoute
  '/mappings/': typeof AuthenticatedMappingsIndexRoute
  '/metrics/': typeof AuthenticatedMetricsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesByTo {
  '/connect': typeof authConnectRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/beans': typeof AuthenticatedBeansIndexRoute
  '/caches': typeof AuthenticatedCachesIndexRoute
  '/conditions': typeof AuthenticatedConditionsIndexRoute
  '/configprops': typeof AuthenticatedConfigpropsIndexRoute
  '/env': typeof AuthenticatedEnvIndexRoute
  '/health': typeof AuthenticatedHealthIndexRoute
  '/loggers': typeof AuthenticatedLoggersIndexRoute
  '/mappings': typeof AuthenticatedMappingsIndexRoute
  '/metrics': typeof AuthenticatedMetricsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/connect': typeof authConnectRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/beans/': typeof AuthenticatedBeansIndexRoute
  '/_authenticated/caches/': typeof AuthenticatedCachesIndexRoute
  '/_authenticated/conditions/': typeof AuthenticatedConditionsIndexRoute
  '/_authenticated/configprops/': typeof AuthenticatedConfigpropsIndexRoute
  '/_authenticated/env/': typeof AuthenticatedEnvIndexRoute
  '/_authenticated/health/': typeof AuthenticatedHealthIndexRoute
  '/_authenticated/loggers/': typeof AuthenticatedLoggersIndexRoute
  '/_authenticated/mappings/': typeof AuthenticatedMappingsIndexRoute
  '/_authenticated/metrics/': typeof AuthenticatedMetricsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/connect'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/errors/$error'
    | '/settings/appearance'
    | '/beans/'
    | '/caches/'
    | '/conditions/'
    | '/configprops/'
    | '/env/'
    | '/health/'
    | '/loggers/'
    | '/mappings/'
    | '/metrics/'
    | '/settings/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connect'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/errors/$error'
    | '/settings/appearance'
    | '/beans'
    | '/caches'
    | '/conditions'
    | '/configprops'
    | '/env'
    | '/health'
    | '/loggers'
    | '/mappings'
    | '/metrics'
    | '/settings'
    | '/tasks'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/connect'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/beans/'
    | '/_authenticated/caches/'
    | '/_authenticated/conditions/'
    | '/_authenticated/configprops/'
    | '/_authenticated/env/'
    | '/_authenticated/health/'
    | '/_authenticated/loggers/'
    | '/_authenticated/mappings/'
    | '/_authenticated/metrics/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authConnectRoute: typeof authConnectRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/connect': {
      id: '/(auth)/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof authConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/beans/': {
      id: '/_authenticated/beans/'
      path: '/beans'
      fullPath: '/beans/'
      preLoaderRoute: typeof AuthenticatedBeansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caches/': {
      id: '/_authenticated/caches/'
      path: '/caches'
      fullPath: '/caches/'
      preLoaderRoute: typeof AuthenticatedCachesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conditions/': {
      id: '/_authenticated/conditions/'
      path: '/conditions'
      fullPath: '/conditions/'
      preLoaderRoute: typeof AuthenticatedConditionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configprops/': {
      id: '/_authenticated/configprops/'
      path: '/configprops'
      fullPath: '/configprops/'
      preLoaderRoute: typeof AuthenticatedConfigpropsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/env/': {
      id: '/_authenticated/env/'
      path: '/env'
      fullPath: '/env/'
      preLoaderRoute: typeof AuthenticatedEnvIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health/': {
      id: '/_authenticated/health/'
      path: '/health'
      fullPath: '/health/'
      preLoaderRoute: typeof AuthenticatedHealthIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/loggers/': {
      id: '/_authenticated/loggers/'
      path: '/loggers'
      fullPath: '/loggers/'
      preLoaderRoute: typeof AuthenticatedLoggersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mappings/': {
      id: '/_authenticated/mappings/'
      path: '/mappings'
      fullPath: '/mappings/'
      preLoaderRoute: typeof AuthenticatedMappingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metrics/': {
      id: '/_authenticated/metrics/'
      path: '/metrics'
      fullPath: '/metrics/'
      preLoaderRoute: typeof AuthenticatedMetricsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedBeansIndexRoute: typeof AuthenticatedBeansIndexRoute
  AuthenticatedCachesIndexRoute: typeof AuthenticatedCachesIndexRoute
  AuthenticatedConditionsIndexRoute: typeof AuthenticatedConditionsIndexRoute
  AuthenticatedConfigpropsIndexRoute: typeof AuthenticatedConfigpropsIndexRoute
  AuthenticatedEnvIndexRoute: typeof AuthenticatedEnvIndexRoute
  AuthenticatedHealthIndexRoute: typeof AuthenticatedHealthIndexRoute
  AuthenticatedLoggersIndexRoute: typeof AuthenticatedLoggersIndexRoute
  AuthenticatedMappingsIndexRoute: typeof AuthenticatedMappingsIndexRoute
  AuthenticatedMetricsIndexRoute: typeof AuthenticatedMetricsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedBeansIndexRoute: AuthenticatedBeansIndexRoute,
  AuthenticatedCachesIndexRoute: AuthenticatedCachesIndexRoute,
  AuthenticatedConditionsIndexRoute: AuthenticatedConditionsIndexRoute,
  AuthenticatedConfigpropsIndexRoute: AuthenticatedConfigpropsIndexRoute,
  AuthenticatedEnvIndexRoute: AuthenticatedEnvIndexRoute,
  AuthenticatedHealthIndexRoute: AuthenticatedHealthIndexRoute,
  AuthenticatedLoggersIndexRoute: AuthenticatedLoggersIndexRoute,
  AuthenticatedMappingsIndexRoute: AuthenticatedMappingsIndexRoute,
  AuthenticatedMetricsIndexRoute: AuthenticatedMetricsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authConnectRoute: authConnectRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
